### ISSUE TITLE
Deploying to Heroku not successful- Node wouldn't compile

### ISSUE THREAD

**Issue by theresaluu** [jasonswett/angular-for-rails-developers-issues#13]
I've worked through errors in the heroku deployment, but now Im not sure what the issue is.  
http://stackoverflow.com/questions/40208635/angular-for-rails-developers-book-deploying-angular-on-rails-on-heroku

`Push rejected, failed to compile Node.js app.`

https://github.com/theresaluu/tut-angular-for-rails-developers

I previously had an issue with my package.json because it was missing a comma, but I addressed that .  Any help would be appreciated.

**Comment by jasonswett** [comment]
In the postbuild in package.json, try replacing `ng build` with `ng build --prod`. I had a similar problem myself the other day.

**Comment by theresaluu** [comment]
Ok I got passed that and it deployed but got an uglifier error when loading the page: 

```
2016-10-24T04:05:12.472797+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
2016-10-24T04:05:12.472798+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
2016-10-24T04:05:12.472797+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
2016-10-24T04:05:12.472798+00:00 app[web.1]:    from bin/rails:9:in `require'
2016-10-24T04:05:12.472799+00:00 app[web.1]:    from bin/rails:9:in `<main>'
2016-10-24T04:05:12.579965+00:00 heroku[web.1]: State changed from starting to crashed
2016-10-24T04:05:12.564713+00:00 heroku[web.1]: Process exited with status 1
2016-10-24T04:05:13.166848+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=evening-castle-95407.herokuapp.com request_id=587704f5-bcb9-4d9e-9512-b67017692465 fwd="68.5.37.158" dyno= connect= service= status=503 bytes=
2016-10-24T04:05:13.797369+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=evening-castle-95407.herokuapp.com request_id=ca615283-edf0-411d-a79f-05e07067d06a fwd="68.5.37.158" dyno= connect= service= status=503 bytes=
2016-10-24T04:09:22.622862+00:00 heroku[web.1]: State changed from crashed to starting
2016-10-24T04:09:32.807467+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 49444 -e production`
2016-10-24T04:09:36.548870+00:00 heroku[web.1]: Process exited with status 1
2016-10-24T04:09:36.444428+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'uglifier'. (Bundler::GemRequireError)
2016-10-24T04:09:36.444470+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
2016-10-24T04:09:36.444476+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
2016-10-24T04:09:36.444482+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
2016-10-24T04:09:36.444483+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
2016-10-24T04:09:36.444483+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
2016-10-24T04:09:36.444490+00:00 app[web.1]:    from /app/config/application.rb:7:in `<top (required)>'
2016-10-24T04:09:36.444484+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
2016-10-24T04:09:36.444490+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `require'
2016-10-24T04:09:36.444491+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
2016-10-24T04:09:36.444492+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
2016-10-24T04:09:36.444492+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
2016-10-24T04:09:36.444493+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
2016-10-24T04:09:36.444493+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
2016-10-24T04:09:36.444494+00:00 app[web.1]:    from bin/rails:9:in `require'
2016-10-24T04:09:36.444495+00:00 app[web.1]:    from bin/rails:9:in `<main>'
2016-10-24T04:09:36.563339+00:00 heroku[web.1]: State changed from starting to crashed

```

**Comment by theresaluu** [comment]
Ok, whooo.  Got passed that.  The app deploys but Heroku has a message to check the logs- output below.  Looks like this is a uglifier problem now.  I'm going to troubleshoot it tomorrow.  

```
2016-10-24T04:38:30.937974+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 33266 -e production`
2016-10-24T04:38:34.329405+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels)
 in require': There was an error while trying to load the gem 'uglifier'. (Bundler::GemRequireError)
2016-10-24T04:38:34.329419+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) i
n require'
2016-10-24T04:38:34.329420+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
2016-10-24T04:38:34.329420+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
2016-10-24T04:38:34.329421+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
2016-10-24T04:38:34.329422+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
2016-10-24T04:38:34.329423+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
2016-10-24T04:38:34.329423+00:00 app[web.1]:    from /app/config/application.rb:7:in `<top (required)>'
2016-10-24T04:38:34.329424+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `re
quire'
2016-10-24T04:38:34.329425+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
2016-10-24T04:38:34.329426+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
2016-10-24T04:38:34.329429+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `se
rver'
2016-10-24T04:38:34.329430+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `ru
n_command!'
2016-10-24T04:38:34.329430+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
2016-10-24T04:38:34.329431+00:00 app[web.1]:    from bin/rails:9:in `require'
2016-10-24T04:38:34.329432+00:00 app[web.1]:    from bin/rails:9:in `<main>'
2016-10-24T04:38:34.467647+00:00 heroku[web.1]: State changed from starting to crashed
2016-10-24T04:38:34.456827+00:00 heroku[web.1]: Process exited with status 1
2016-10-24T04:38:34.682092+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=evening-castle-95407.herokuapp.com reque
st_id=8a609185-9ba7-4604-9359-9df9ceaed8dc fwd="68.5.37.158" dyno= connect= service= status=503 bytes=
2016-10-24T04:42:10.029076+00:00 heroku[slug-compiler]: Slug compilation started
2016-10-24T04:42:10.029081+00:00 heroku[slug-compiler]: Slug compilation finished
2016-10-24T04:42:09.838732+00:00 heroku[api]: Deploy ebe70dd by theresa.luu@gmail.com
2016-10-24T04:42:09.838794+00:00 heroku[api]: Release v8 created by theresa.luu@gmail.com
2016-10-24T04:42:10.619027+00:00 heroku[web.1]: State changed from crashed to starting
```

**Comment by jasonswett** [comment]
Any luck getting past this?

**Comment by theresaluu** [comment]
@jasonswett No.  Uninstalled npm and reinstalled it without home-brew because I ran into some home-brew errors while I was verifying that I had the versions of npm and node that you suggested in the book.  I also downloaded the book updates which I think did have us do the cors stuff before deploying (I could be wrong, but mine were not done), so I followed those instructions.  Still getting the `There was an error while trying to load the gem 'uglifier'`-error in my Heroku log.

**Comment by jasonswett** [comment]
Hmm, I haven't encountered this one so I can only guess, sorry. Have you seen this? http://stackoverflow.com/questions/34420554/there-was-an-error-while-trying-to-load-the-gem-uglifier-bundlergemrequire

**Comment by theresaluu** [comment]
@jasonswett Actually, the second answer in that post (author: user3780968) helped me.  I just had to uncomment out therubyracer gem.  I, also, updated the uglifier gem (which did nothing by itself).  I can finally move on to the next steps now.  =)
